TwP/logging

lib/logging/color_scheme.rb
As the original author of `color_scheme.rb` I am explicitly stating that it is under the terms of the MIT license to keep it under the same license as the logging gem.
=> explicitly state that color_scheme.rb is MIT license

lib/logging.rb, lib/logging/appender.rb, lib/logging/filter.rb, lib/logging/filters.rb, lib/logging/filters/level.rb, test/test_appender.rb, test/test_filter.rb, test/test_logger.rb
Logging::Filter provides a base class for implementing arbitrary
event-based filtering of log events.
Logging::Filter::Level implements this to limit log messages to an
appender to only those that match a specific, enumerated list of log
levels.
=> Filtering mechanism similar to log4j or slf4j filters

lib/logging/layouts/pattern.rb
As has been pointed out already in #98, the code to build up the `format` method for the Pattern layout is very obtuse and hard to follow. The goal of this refactoring is to pull the massive `case` statement out into a builder class that is easier to reason about and easier to maintain.
=> Refactor the pattern layout builder

Rakefile, test/appenders/test_buffered_io.rb, test/appenders/test_file.rb
Making the appender tests more resilient in the face of default encodings specified in the environment. Also cleaning up the Rakefile a bit.
closes #114 
closes #115
=> Encodings!

lib/logging/appenders/file.rb, lib/logging/appenders/rolling_file.rb, lib/logging/appenders/syslog.rb, test/appenders/test_file.rb, test/appenders/test_rolling_file.rb, test/appenders/test_syslog.rb
In order to create a syslog appender, the user must supply a name. The factory method should reflect this issue with a validation.
The previous implementation returned a class, not an instance. This led to errors like this:
```
ArgumentError: unknown appender Logging::Appenders::Syslog
add_appenders at /Users/olle/.rvm/gems/jruby-1.7.18/gems/logging-2.0.0/lib/logging/logger.rb:321
each at org/jruby/RubyArray.java:1613
add_appenders at /Users/olle/.rvm/gems/jruby-1.7.18/gems/logging-2.0.0/lib/logging/logger.rb:319
(root) at o.rb:3
```
My test program was:
```ruby
require 'logging'
l = Logging::Logger['mongrel']
l.add_appenders( Logging.appenders.syslog )
l.level = :info
l.warn "HEJ!"
```
The test program will now raise an explicit error when the user has not supplied any arguments to the …
=> syslog, file, rolling_file appender factory methods: Fail explicitly on bad arguments

lib/logging/log_event.rb
Sometimes I have traces like this one : ```/home/akarzim/project/app/models/foo.rb:147:in `rescue in foo'```
In order to get the method name, I have updated the CALLER_RGXP regular expression to allow whitespaces in method name.
=> allow whitespaces in traced method name

lib/logging/appender.rb, lib/logging/logger.rb, test/test_appender.rb, test/test_logger.rb
It's very confusing when `logger.to_s` or `"#{logger}"` show different
object ids than `logger.inspect`. This makes the custom `inspect`
implementation match Ruby's default formatting of object ids.
=> Make object id in #inspect match default behavior

lib/logging/layout.rb, test/test_layout.rb
The `backtrace` flag for layouts needs a little love. This change adds setter and getter methods for this flag.
=> Accessors for setting the backtrace flag

lib/logging/layouts/pattern.rb, test/performance.rb
Since the Ruby 1.9 release, the `Time#strftime` method has supported native output of microsecond reoslution time stamps. Fixing the date formatting code in the Pattern layout to use this native `%6N` `strftime` format dramatically improves logging performance.
=> Improve date format performance

lib/logging/appenders/buffering.rb, test/appenders/test_async_flushing.rb, test/appenders/test_periodic_flushing.rb, test/benchmark.rb
These changes enable the existing periodic flushing mechanism to be used to asynchronously write the log buffer to the IO stream. By setting the `async` flag to true, the flusher Thread will be used to write messages thereby freeing up the main program thread to continue on doing other work.
refs #130 
/cc @thedrow
=> Enable asynchronous writes of the log buffer

History.txt, lib/logging/logger.rb
The goal of this PR is to address some thread safety issues in the Logging framework. Namely assigning log levels to Loggers.
Because we have a hierarchy of Loggers, assigning a log level to one Logger affects all the children under that part of the hierarchy. The changes here lock the hierarchy via a mutex so that only one thread can modify the log levels at any given time.
refs #129 and #132 
/cc @perlun
=> Thread safe log level

History.txt, lib/logging/appenders/console.rb, lib/logging/appenders/io.rb, lib/logging/appenders/rolling_file.rb
Setting the `sync` flag to true on the IO stream and using the standard `write` method is just as performant as using `syswrite`. For the sake of avoiding unexpected surprises with mixed write/syswrite operations, I'm switching everything over to plain writes.
refs #127
=> Removing use of syswrite

.travis.yml
This PR proposes to build with newer versions of Ruby.
Versions taken from [ruby-build](https://github.com/rbenv/ruby-build/tree/master/share/ruby-build), the repository with build descriptions
=> Travis: Use latest stable Ruby, JRuby

lib/logging/appenders/rolling_file.rb
There is a race condition in determining the modification time of the "copy file" used for the copy/truncate rolling semantics. We first check if the file exists, but under some conditions the copy file can be deleted before the `mtime` is determined. This leads to an `ENOENT` exception.
The fix here is to let the exception happen, catch it, and return a `nil` modification time.
fixes #148
=> Fix a race condition in the rolling file appender

README.md
The consolidation example was removed in 2.1.0.
Close #143.
=> Remove link to non-existent example

lib/logging.rb, lib/logging/log_event.rb, test/test_log_event.rb, test/test_logging.rb
This PR adds a `basepath` configuration for the Logging framework. When call tracing is enabled for log events, the reported filenames will be relative to this `basepath` setting.
```ruby
Logging.basepath = Rails.root.to_s
```
Now for your Rails project, all filenames are relative to that path. Messages will contain filenames like this `app/model/user.rb` instead of the longer `/home/sally/projects/rails_app/app/model/user.rb`.
fixes #126 
/cc @cshupp1 and @vanso-hubsi since you both might have some thoughts on the approach taken here
=> Base path for file names

lib/logging.rb, lib/logging/layout.rb, lib/logging/layouts/parseable.rb, lib/logging/layouts/pattern.rb, lib/logging/log_event.rb, test/layouts/test_json.rb, test/layouts/test_pattern.rb, test/layouts/test_yaml.rb, test/test_layout.rb, test/test_logging.rb
The goal of this PR is to allow the timestamps generated by the various layout classes to be represented in specific timezones. Currently only the system local timezone is used when generating timestamps. The changes in this PR allow the user to configure a `utc_offset` for timestamps. With this setting enabled, layouts will adjust times to the desired `utc_offset` before formatting the timestamp.
```ruby
Logging.utc_offset = "UTC"
```
With the above configuration, all timestamps for all layouts will be formatted in the UTC timezone. The layouts themselves can override this default when they are first created.
```ruby
Logging.utc_offset = "+01:00"
Logging.layouts.json(:utc_offset => "UTC")  # times are formatted in UTC
Logging.layouts.pattern  # times are formatted in Central European …
```
=> Support UTC offset

lib/logging/diagnostic_context.rb, test/test_mapped_diagnostic_context.rb, test/test_nested_diagnostic_context.rb
This code adds an environment flag that can be used to disable or enabled context inheritance. The diagnostic contexts are stored in a thread local variable. To inhert this context between threads, we have to override the `new`, `start`, and `fork` methods so that we have a handle on the parent thread's context.
The unfortunate downside of this is that we end up with `Logging` calls in backtraces for some exceptions involving threads. This can lead to confusion.
You can set the environment variable `LOGGING_INHERIT_CONTEXT` to `false` to disable this feature if you do not need it.
```sh
LOGGING_INHERIT_CONTEXT=false ruby your_code.rb
```
fixes #155
/cc @ivoanjo
=> Make context inheritance optional

.travis.yml, lib/logging.rb, lib/logging/appenders/console.rb, lib/logging/color_scheme.rb, lib/logging/diagnostic_context.rb
When the Logging gem was originally written, Ruby Fibers did not exist. The syntax for setting a thread local variable was originally:
```ruby
Thread.current["variable"] = "value"
```
But with the advent of fibers, the meaning of the above syntax changed. Instead this syntax sets fiber local variables, and the syntax for setting a thread local variable changed to be:
```ruby
Thread.current.thread_variable_set("variable", "value")
```
This PR changes the Logging code back to using thread local variables as was the original intent.
=> Use thread-local variables for diagnostic contexts

.gitignore, lib/logging/layout.rb, lib/logging/layouts/parseable.rb, test/layouts/test_nested_exceptions.rb
It outputs an exception and its causes recursively for ruby 2.1 and after.
=> Add support for formatting nested exceptions.

lib/logging.rb, lib/logging/layout.rb, lib/logging/layouts/parseable.rb, test/layouts/test_nested_exceptions.rb, test/test_logging.rb
Adding a limit the number of nested exceptions that can show up when printing exception errors via a layout. Also cleaning up the backtraces to remove gobs of duplicate backtrace lines.
=> Exception cause cleanup

lib/logging.rb, test/test_logging.rb
This adds `Logger.raise_errors` as an alternative to `Thread.abort_on_exception`. to raise errors when an unhandleable internal error occurs. `Thread.abort_on_exception` has a lot of dangerous side effects that aren't always appropriate.
=> Add Logger.raise_errors

lib/logging/logger.rb
Creating a new logger while also updating the level of an existing
logger can produce
```
can't add a new key into hash during iteration
```
because both operate on the same hash of loggers but use different
mutexes. Update them to share the same mutex.
Fixes #200.
=> Fix Logging::Logger#level= to be thread-safe

lib/logging/appenders/file.rb, lib/logging/appenders/io.rb, test/appenders/test_file.rb
There is a race condition in the File appender where two processes can attempt to open the same file at the same time. The changes here account for this by separating file opening from file creation.
Thanks to @sonots and his work fixing this same issue in the core Ruby Logger class. I've followed his approach to solve the same problem.
=> Handle simultaneous process startup

examples/appenders.rb
Noticed this while reading the examples. Thanks!
=> Fix spelling in documentation

lib/logging/appenders/rolling_file.rb
There is a bug in the log rolling code where multiple threads in the same process can contend on rolling the files. The result is that we will delete log files and drop log messages. I grabbed the example from @lzap and modified the code a bit to get a better handle on the error.
```ruby
require 'logging'
filename = "tmp/rolling.log"
Logging.raise_errors = true
Logging.appenders.rolling_file filename,
keep: 20,
size: 400_000,
age: 2,
layout: Logging.layouts.pattern(pattern: "[%d] %T %5l -- %c: %m\n")
log = Logging.logger.root
log.add_appenders(Logging.appenders[filename])
log.level = :debug
threads = []
(1..30).each { |thread_count|
threads << Thread.new do
Thread.current[:name] = "T-%02d" % thread_count
(1..1_000).each { |n|
log.debug "#{n} a very nice little debug message"
log.warn …
```
=> Synchronize log rolling

lib/logging/appenders/file.rb, lib/logging/appenders/rolling_file.rb, test/appenders/test_file.rb, test/appenders/test_rolling_file.rb, test/setup.rb, test/test_logging.rb
This PR fixes a race condition when multiple processes are attempting to create the same log file at startup. The solution is to try to open the file and fallback to creating if opening doesn't work. This solution has been applied to both the normal file appender and the rolling file appender.
=> Fix file creation race

lib/logging/layouts/parseable.rb, lib/logging/layouts/pattern.rb, lib/logging/log_event.rb, test/layouts/test_json.rb, test/layouts/test_pattern.rb, test/layouts/test_yaml.rb, test/test_log_event.rb
Renaming the `LogEvent#method` accessor to avoid conflicting with `Kernel#method`. This will cause exceptions when other classes attempt to invoke `method` on LogEvent with the wrong number of arguments.
fixes #211
=> Rename method to avoid conflict with Kernel

lib/logging/appenders/console.rb, test/appenders/test_console.rb
This PR changes how the `Stdout` and `Stderr` conosle appenders work. Instead of reusing the Ruby constants `STDOUT` and `STDERR`, these appenders now create their own IO objects to use under the hood. These appenders have better behavior and can be closed and reopened.
fixes #214
=> Fix up console appenders

lib/logging/appenders/console.rb, lib/logging/appenders/io.rb, lib/logging/log_event.rb, test/appenders/test_console.rb
This PR includes two fixes for JRuby:
* closing copies of `STDOUT` IO streams would cause JRuby to hang - fixes #235 
* caller tracing stacks have changed with JRuby 9
The fix here is to no longer create copies of `STDOUT` and `STDERR`. Instead, we just check if the underlying IO object is one of these two and then don't bother closing them.
=> Fixes for JRuby

logging.gemspec
Without the license being set, rubygems does not display the correct
license information.
=> Add license to gemspec file
